/**
 * Ohio Rate Watch — Historical Rate Chart
 * Interactive Chart.js line chart showing SCO rate history, Henry Hub, and best fixed rate
 * Generated by: Opus (sub-agent, Chart Prototype)
 * Date: 2025-02-25 EST
 */

(function () {
  'use strict';

  const CHART_COLORS = {
    sco: '#e53935',        // red — matches logo accent
    henryHub: '#1565c0',   // blue — matches site primary
    bestFixed: '#16a34a',  // green — matches savings color
    eventLine: '#9ca3af',
    gridLine: '#f0f0f0',
    tooltipBg: '#1a1a2e',
  };

  async function init() {
    const canvas = document.getElementById('rate-history-chart');
    if (!canvas) return;

    let data;
    try {
      const res = await fetch('/api/history/chart-data');
      data = await res.json();
    } catch (err) {
      console.error('Failed to load chart data:', err);
      canvas.parentElement.innerHTML = '<p style="color:#999;text-align:center;padding:40px;">Chart data unavailable. Please try again later.</p>';
      return;
    }

    const labels = data.sco.map(d => d.date);
    const scoValues = data.sco.map(d => d.value);
    const henryValues = data.henryHub.map(d => d.value);

    // Build event annotation lines
    const annotations = {};
    data.events.forEach((evt, i) => {
      const idx = labels.indexOf(evt.date);
      if (idx === -1) return;
      annotations['event' + i] = {
        type: 'line',
        xMin: evt.date,
        xMax: evt.date,
        borderColor: 'rgba(156,163,175,0.5)',
        borderWidth: 1,
        borderDash: [4, 4],
        label: {
          display: true,
          content: evt.icon + ' ' + evt.label,
          position: 'start',
          backgroundColor: 'rgba(255,255,255,0.9)',
          color: '#374151',
          font: { size: 10, weight: '600' },
          padding: { top: 3, bottom: 3, left: 6, right: 6 },
          borderRadius: 4,
        }
      };
    });

    // Best fixed rate reference line
    annotations['bestFixed'] = {
      type: 'line',
      yMin: data.bestFixed,
      yMax: data.bestFixed,
      borderColor: CHART_COLORS.bestFixed,
      borderWidth: 2,
      borderDash: [8, 4],
      label: {
        display: true,
        content: 'Best Fixed: $' + data.bestFixed.toFixed(3) + '/ccf',
        position: 'end',
        backgroundColor: CHART_COLORS.bestFixed,
        color: '#fff',
        font: { size: 11, weight: '700' },
        padding: { top: 4, bottom: 4, left: 8, right: 8 },
        borderRadius: 4,
      }
    };

    new Chart(canvas, {
      type: 'line',
      data: {
        labels,
        datasets: [
          {
            label: 'SCO Rate ($/ccf)',
            data: scoValues,
            borderColor: CHART_COLORS.sco,
            backgroundColor: 'rgba(229,57,53,0.08)',
            borderWidth: 2.5,
            pointRadius: 3,
            pointHoverRadius: 6,
            pointBackgroundColor: CHART_COLORS.sco,
            fill: true,
            tension: 0.3,
          },
          {
            label: 'Henry Hub ($/ccf equiv.)',
            data: henryValues,
            borderColor: CHART_COLORS.henryHub,
            backgroundColor: 'transparent',
            borderWidth: 2,
            pointRadius: 2,
            pointHoverRadius: 5,
            pointBackgroundColor: CHART_COLORS.henryHub,
            borderDash: [5, 3],
            fill: false,
            tension: 0.3,
          },
        ],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        interaction: {
          mode: 'index',
          intersect: false,
        },
        plugins: {
          legend: {
            position: 'top',
            labels: {
              usePointStyle: true,
              padding: 16,
              font: { size: 12, weight: '600' },
            },
          },
          tooltip: {
            backgroundColor: CHART_COLORS.tooltipBg,
            titleFont: { size: 13, weight: '700' },
            bodyFont: { size: 12 },
            padding: 12,
            cornerRadius: 8,
            callbacks: {
              title: function (items) {
                const d = items[0].label;
                const [y, m] = d.split('-');
                const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
                return months[parseInt(m) - 1] + ' ' + y;
              },
              label: function (ctx) {
                return ctx.dataset.label + ': $' + ctx.parsed.y.toFixed(3) + '/ccf';
              },
            },
          },
          annotation: {
            annotations,
          },
        },
        scales: {
          x: {
            grid: { display: false },
            ticks: {
              font: { size: 11 },
              color: '#9ca3af',
              maxRotation: 45,
              callback: function (val, idx) {
                const label = this.getLabelForValue(val);
                if (typeof label !== 'string') return label;
                const [y, m] = label.split('-');
                if (m === '01' || m === '07') {
                  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
                  return months[parseInt(m) - 1] + ' ' + y;
                }
                return '';
              },
            },
          },
          y: {
            beginAtZero: false,
            min: 0.15,
            grid: { color: CHART_COLORS.gridLine },
            ticks: {
              font: { size: 11 },
              color: '#9ca3af',
              callback: function (val) {
                return '$' + val.toFixed(2);
              },
            },
            title: {
              display: true,
              text: '$/ccf',
              font: { size: 12, weight: '600' },
              color: '#6b7280',
            },
          },
        },
      },
      plugins: [],
    });
  }

  // Wait for Chart.js and annotation plugin to load
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
